// <auto-generated />
using AquaStoreAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AquaStoreAPI.Migrations
{
    [DbContext(typeof(AquaStoreDBContext))]
    partial class AquaStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AquaStoreAPI.Models.Aquarium", b =>
                {
                    b.Property<int>("AquariumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("FishID")
                        .HasColumnType("int");

                    b.Property<string>("GlassType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shape")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AquariumID");

                    b.HasIndex("FishID");

                    b.ToTable("Aquaria");
                });

            modelBuilder.Entity("AquaStoreAPI.Models.Fish", b =>
                {
                    b.Property<int>("FishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Fins")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FishID");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("AquaStoreAPI.Models.Aquarium", b =>
                {
                    b.HasOne("AquaStoreAPI.Models.Fish", "Fish")
                        .WithMany()
                        .HasForeignKey("FishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fish");
                });
#pragma warning restore 612, 618
        }
    }
}
